const EVENT_KEY_ORDER = [
  'slug',
  'title',
  'summary',
  'description',
  'startDate',
  'endDate',
  'allDay',
  'use_daily_schedule',
  'daily_schedule',
  'recurrence',
  'category',
  'town',
  'locationName',
  'address',
  'lat',
  'lng',
  'priceType',
  'priceNote',
  'badges',
  'image',
  'organizerName',
  'organizerUrl',
  'eventUrl',
  'icsUrl',
  'featured',
  'hidden',
  'archived',
  'status',
  'source',
  'sourceRef',
  'updatedAt',
]

const CATEGORY_OPTIONS = [
  'Family',
  'Festivals',
  'Sports',
  'Golf',
  'Markets',
  'Arts & Culture',
  'Outdoors',
  'Other',
]

const TOWN_OPTIONS = [
  'Aurora',
  'Uxbridge',
  'Georgina',
  'Stouffville',
  'East Gwillimbury',
  'Newmarket',
  'Scugog',
  'Toronto-adjacent',
]

const BADGE_OPTIONS = [
  'Family-friendly',
  'Seasonal',
  'Outdoors',
  'Pets OK',
  'Accessible',
]

const ISO_DATETIME_PATTERN = '^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}Z$'

const EVENT_SCHEMA = {
  $id: 'https://finallyhomeagents.github.io/schemas/events/cms-event.json',
  type: 'object',
  additionalProperties: false,
  required: [
    'slug',
    'title',
    'summary',
    'description',
    'startDate',
    'allDay',
    'use_daily_schedule',
    'category',
    'town',
    'locationName',
    'address',
    'priceType',
    'eventUrl',
    'featured',
    'hidden',
    'archived',
    'status',
    'source',
  ],
  properties: {
    slug: { type: 'string', pattern: '^[a-z0-9-]+$' },
    title: { type: 'string' },
    summary: { type: 'string' },
    description: { type: 'string' },
    startDate: { type: 'string', pattern: ISO_DATETIME_PATTERN },
    endDate: { type: 'string', pattern: ISO_DATETIME_PATTERN },
    allDay: { type: 'boolean' },
    use_daily_schedule: { type: 'boolean' },
    daily_schedule: {
      type: 'array',
      items: {
        type: 'object',
        additionalProperties: false,
        required: ['date', 'all_day', 'start_time', 'end_time'],
        properties: {
          date: { type: 'string', pattern: '^\\d{4}-\\d{2}-\\d{2}$' },
          all_day: { type: 'boolean' },
          start_time: { type: 'string', pattern: '^(?:\\d{2}:\\d{2})?$' },
          end_time: { type: 'string', pattern: '^(?:\\d{2}:\\d{2})?$' },
        },
      },
    },
    recurrence: { type: 'string' },
    category: { type: 'string', enum: CATEGORY_OPTIONS },
    town: { type: 'string', enum: TOWN_OPTIONS },
    locationName: { type: 'string' },
    address: { type: 'string' },
    lat: { type: 'number' },
    lng: { type: 'number' },
    priceType: { type: 'string', enum: ['Free', 'Paid', 'Mixed'] },
    priceNote: { type: 'string' },
    badges: {
      type: 'array',
      items: { type: 'string', enum: BADGE_OPTIONS },
      uniqueItems: true,
    },
    image: { type: 'string' },
    organizerName: { type: 'string' },
    organizerUrl: { type: 'string' },
    eventUrl: { type: 'string' },
    icsUrl: { type: 'string' },
    featured: { type: 'boolean' },
    hidden: { type: 'boolean' },
    archived: { type: 'boolean' },
    status: { type: 'string', enum: ['draft', 'pending', 'approved', 'published', 'archived'] },
    source: { type: 'string', enum: ['manual', 'feed'] },
    sourceRef: { type: 'string' },
    updatedAt: { type: 'string', pattern: ISO_DATETIME_PATTERN },
  },
}

module.exports = {
  EVENT_SCHEMA,
  EVENT_KEY_ORDER,
  CATEGORY_OPTIONS,
  TOWN_OPTIONS,
  BADGE_OPTIONS,
}
