import { escapeHtml as e } from './core.mjs'
export function publicPage(posts, selected) {
  const p = selected
  const title = p
    ? `${p.title} | NorthSide GTA Life`
    : 'NorthSide GTA Life | Discover what makes it home'
  const url = p
    ? `https://northsidegta.ca/life/posts/${p.id}`
    : 'https://northsidegta.ca/life/'
  const intro =
    'Local places. Everyday discoveries. With Matthew & Landon Mulhall, Finally Home Agents.'
  return `<!doctype html><html lang="en-CA"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${e(title)}</title><meta name="description" content="${e(p?.website?.slice(0, 155) || intro)}"><link rel="canonical" href="${url}"><meta property="og:title" content="${e(title)}"><meta property="og:description" content="${e(p?.website?.slice(0, 155) || intro)}">${p?.image ? `<meta property="og:image" content="${e(p.image)}">` : ''}<link rel="stylesheet" href="/life/studio/style.css"></head><body class="public-page"><header class="public-header"><a class="brand" href="/">NORTHSIDE GTA<span>Life</span></a><a class="text-link" href="/contact">Meet Matthew & Landon ↗</a></header><main class="public-main">${p ? `<a class="text-link" href="/life/">← All local discoveries</a><p class="eyebrow">${e(p.community)} · ${e(p.place)}</p><h1>${e(p.title)}</h1><p class="muted">Shared by ${e(p.author)} · Finally Home Agents</p><img class="story-image" src="${e(p.image)}" alt="${e(p.alt)}"><div class="story-copy">${e(p.website).replace(/\n/g, '<br>')}</div>` : `<p class="eyebrow">THE PEOPLE. THE PLACES. THE EVERYDAY.</p><h1>Discover what<br>makes it <em>home.</em></h1><p class="intro">${intro}</p><div class="filter-row"><label>Explore by community <select id="community-filter"><option value="">All communities</option>${[...new Set(posts.map((x) => x.community))].map((c) => `<option>${e(c)}</option>`).join('')}</select></label></div><div class="public-grid">${posts.length ? posts.map((x) => `<article class="discovery" data-community="${e(x.community)}"><a href="/life/posts/${x.id}"><img src="${e(x.image)}" alt="${e(x.alt)}" loading="lazy"><div><p class="eyebrow">${e(x.community)}</p><h2>${e(x.title)}</h2><p>${e(x.place)}</p></div></a></article>`).join('') : '<div class="empty-state"><h2>Our first discoveries are on the way.</h2><p>Local moments from Matthew and Landon, coming soon.</p></div>'}</div>`}<aside class="contact-card"><p class="eyebrow">YOUR LOCAL REAL ESTATE GUIDES</p><h2>Get to know the place.<br>Then find your home.</h2><p>Considering a move? Matthew and Landon can help you explore your options.</p><a class="button primary" href="/contact">Talk with Matthew & Landon ↗</a></aside></main><footer class="public-footer">Matthew & Landon Mulhall · Finally Home Agents<br>HomeLife Optimum Realty, Brokerage · <a href="/privacy">Privacy</a></footer><script src="/life/studio/feed.js" defer></script></body></html>`
}
