export const didYouKnowFacts = [
  "Did you know you can grab a latte at Nexus Coffee on Main Street Uxbridge and be on the Trans Canada Trail in less than five minutes?",
  "Did you know Stouffville’s GO Train can get you to downtown Toronto in under an hour?",
  "Did you know the Riverwalk Commons in Newmarket turns into a free outdoor skating rink every winter, complete with lights and music?",
  "Did you know you can enjoy lake views year-round in Georgina, with beaches, marinas, and parks all along the Lake Simcoe shoreline?",
  "Did you know Port Perry’s waterfront park hosts live music, farmers’ markets, and community festivals all summer long — just steps from Lake Scugog?",
  "Did you know you can tee off at Mill Run Golf Club in Uxbridge and finish your round with views that stretch across the Oak Ridges Moraine?",
  "Did you know Aurora has over 60 parks connected by a network of trails, so you can walk, run, or bike almost anywhere in town?",
  "Did you know you can dine at Joia on Main or stay at the beautifully restored Postmark Hotel — both right in the heart of Newmarket’s historic Main Street?",
  "Did you know Stouffville’s Bruce’s Mill Conservation Park hosts the annual Sugarbush Maple Syrup Festival every spring — complete with tastings, wagon rides, and family fun?",
  "Did you know Uxbridge’s Roxy Theatre is one of Ontario’s last independent cinemas, complete with vintage charm and fresh popcorn every night?",
  "Did you know East Gwillimbury’s Green Lane area has everything from big-box shopping to fresh local markets — all just minutes from the GO Station?",
  "Did you know Stouffville borders Rouge National Urban Park, giving residents access to Canada’s largest urban park for hiking, biking, and nature walks?",
  "Did you know Port Perry’s Victorian-style downtown has been featured in dozens of movies and TV shows because of its small-town charm?",
  "Did you know Newmarket’s Riverwalk Commons transforms into a lively plaza in summer with splash pads, concerts, and outdoor movies under the stars?",
  "Did you know you can enjoy locally roasted coffee and baked goods at The Naked Café in Uxbridge before exploring the nearby Trans Canada Trail?",
  "Did you know Georgina’s Sibbald Point Provincial Park offers one of the best sandy beaches on Lake Simcoe — perfect for summer picnics and swimming?",
  "Did you know Aurora’s Town Park hosts weekly farmers’ markets from spring to fall, featuring local produce, baked goods, and live music?",
  "Did you know Stouffville’s Memorial Park is home to concerts, festivals, and outdoor movies all summer long?",
  "Did you know Uxbridge’s Wooden Sticks Golf Club was inspired by famous holes from around the world, including Augusta and St Andrews?",
  "Did you know Georgina is home to over a dozen public beaches along Lake Simcoe, each with its own unique shoreline and picnic spots?",
  "Did you know Aurora’s historic downtown is filled with boutique shops, cafés, and restaurants, all within walking distance of the GO Station?",
  "Did you know Newmarket’s Tom Taylor Trail connects 11 parks across town, making it one of York Region’s most scenic walking and cycling routes?",
  "Did you know Port Perry’s Great Blue Heron Casino & Hotel offers live entertainment, dining, and weekend getaways just minutes from the waterfront?",
  "Did you know Stouffville’s Main Street is lined with locally owned cafés, restaurants, and shops that host live music and community events year-round?",
  "Did you know Uxbridge sits atop the Oak Ridges Moraine, giving it rolling hills, fresh air, and some of the most beautiful scenery in the GTA?",
  "Did you know Georgina’s waterfront trails connect parks, beaches, and marinas — perfect for a morning jog or sunset walk along Lake Simcoe?",
  "Did you know Aurora’s Stronach Recreation Complex features ice pads, a pool, and fitness facilities for year-round community programs?",
  "Did you know East Gwillimbury’s Sharon Library branch doubles as a community hub with workshops, kids’ programs, and local art exhibits?",
  "Did you know Stouffville is surrounded by golf courses — including Spring Lakes, Ballantrae, and Rolling Hills — all within a 10-minute drive?",
  "Did you know Newmarket’s Upper Canada Mall features over 200 stores, plus restaurants and cafés perfect for a weekend outing?",
  "Did you know Port Perry’s waterfront trail wraps around Lake Scugog and connects directly to the shops and cafés downtown?",
  "Did you know Aurora’s Magna Golf Club hosted the LPGA Tour’s Canadian Women’s Open in 2019?",
  "Did you know Uxbridge’s annual Fall Fair has been running for over 160 years, celebrating local farming, food, and family fun?",
  "Did you know East Gwillimbury is one of York Region’s fastest-growing communities, with new parks, schools, and trails opening every year?",
  "Did you know Georgina’s Jackson’s Point offers lakefront dining, boutique shopping, and some of the best sunset views on Lake Simcoe?",
  "Did you know Newmarket’s Fairy Lake Park connects directly to Main Street, making it easy to grab lunch, stroll the trails, or catch a festival?",
  "Did you know Stouffville’s 9th Line corridor is home to new schools, parks, and community centres built for growing families?",
  "Did you know East Gwillimbury’s Queensville Community Centre includes sports courts, a pool, and recreation areas for families?",
  "Did you know the NorthSide GTA is home to over 30 golf courses — from championship layouts like Wooden Sticks to hidden forest fairways?",
  "Did you know Uxbridge is surrounded by ski hills like Lakeridge, Dagmar, and Skyloft — making it one of the best spots in the GTA for winter fun?",
  "Did you know Dr. G.W. Williams Secondary School in Aurora scored 8.8/10 and ranked 28th out of 746 Ontario high schools in the 2024 Fraser Institute report?",
  "Did you know residents of Georgina can reach the south shore of Lake Simcoe in under 10 minutes from most neighbourhoods?",
  "Did you know Stouffville has more than 30 kilometres of public trails connecting parks, schools, and neighbourhoods across town?",
  "Did you know Aurora’s St. Andrew’s College is one of Canada’s leading independent schools, with a 125-year history of academics and athletics?",
  "Did you know Georgina’s new Multi-Use Recreation Complex features an Olympic-sized pool, gymnasiums, and year-round community programs?"
];
