import React, { useEffect, useRef, useState } from "react";
import { Helmet } from "react-helmet-async";
import { ArrowRight, Check, ChevronRight, LockKeyhole, Users, Handshake, BriefcaseBusiness } from "lucide-react";
import "./BusinessNetworkPage.css";

const BRAND = "Good Good Business Network"; // Working brand pending formal trademark clearance.
const categories = ["Accounting","Automotive","Commercial Banking","Construction","Electrical","Financial Planning","HVAC","Insurance","Law","Marketing & Advertising","Mortgage & Lending","Plumbing","Real Estate","Technology / IT"];
const principles = [
  { icon: BriefcaseBusiness, n:"01", title:"One seat.", text:"One carefully selected member represents each business category." },
  { icon: LockKeyhole, n:"02", title:"Selected, not sold.", text:"An open category means applications are being considered. It does not reserve the seat." },
  { icon: Handshake, n:"03", title:"Contribution matters.", text:"Members are expected to create introductions, share knowledge and help others move forward." },
  { icon: Users, n:"04", title:"The right room.", text:"Preference is given to Mill Run members and people with a strong connection to the community." }
];

export default function BusinessNetworkPage(){
 const [open,setOpen]=useState(false);
 const [step,setStep]=useState(1);
 const [sent,setSent]=useState(false);\n const [submitting,setSubmitting]=useState(false);\n const [submitError,setSubmitError]=useState("");
 const formRef=useRef(null);
 const [form,setForm]=useState(()=>{
  const empty={name:"",company:"",role:"",email:"",phone:"",website:"",linkedin:"",companySize:"",market:"",category:"",years:"",millRun:"",connection:"",business:"",why:"",contribution:"",example:"",connections:"",expertise:"",whyYou:"",sixMonths:"",goal:"",desiredCategories:"",commit:"",feeComfort:"",referrer:"",agree:false};
  if(typeof window==="undefined") return empty;
  try{return {...empty,...JSON.parse(window.localStorage.getItem("good-good-application")||"{}")};}catch{return empty;}
 });
 useEffect(()=>{try{window.localStorage.setItem("good-good-application",JSON.stringify(form));}catch{}},[form]);
 const set=(k,v)=>setForm(f=>({...f,[k]:v}));
 const next=()=>{const formEl=formRef.current;if(!formEl)return;const visible=[...formEl.querySelectorAll("section")].find(s=>s.offsetParent!==null);const invalid=visible?.querySelector(":invalid");if(invalid){invalid.reportValidity();invalid.focus();return;}setStep(s=>Math.min(4,s+1));window.scrollTo({top:0,behavior:"smooth"});};
 const submit=async e=>{e.preventDefault();if(!e.currentTarget.reportValidity())return;setSubmitting(true);setSubmitError("");try{const response=await fetch("/api/good-good-applications?action=submit",{method:"POST",headers:{"Content-Type":"application/json","Accept":"application/json"},body:JSON.stringify({...form,nickname:""})});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||"We couldn’t submit your application. Please try again.");try{window.localStorage.removeItem("good-good-application");}catch{}setSent(true);window.scrollTo({top:0,behavior:"smooth"});}catch(error){setSubmitError(error.message);window.scrollTo({top:document.body.scrollHeight,behavior:"smooth"});}finally{setSubmitting(false);}};
 if(sent) return <main className="bn"><Helmet><title>Application Received | {BRAND}</title></Helmet><section className="bn-success"><div className="bn-mark">GG</div><p className="bn-kicker">APPLICATION RECEIVED</p><h1>Thank you, {form.name.split(" ")[0]||"there"}.</h1><p>Your application for the <strong>{form.category||"selected"}</strong> seat has been received. Applications are reviewed individually. If there may be a mutual fit, you'll be contacted for a short conversation.</p><div className="bn-success-rule">No payment. No automatic acceptance.</div></section></main>;
 if(open) return <main className="bn bn-formpage"><Helmet><title>Apply for Membership | {BRAND}</title></Helmet><header className="bn-mini"><button onClick={()=>setOpen(false)} className="bn-wordmark"><span className="bn-mark">GG</span><span><b>GOOD GOOD</b><small>BUSINESS NETWORK</small></span></button><span>APPLICATION · {step} OF 4</span></header><form ref={formRef} className="bn-application" onSubmit={submit}>
   <div className="bn-progress"><i style={{width:`${step*25}%`}} /></div>
   {step===1&&<section><p className="bn-kicker">01 — ABOUT YOU</p><h1>Apply for your seat.</h1><p className="bn-lede">An open category means we're accepting applications. It does not guarantee acceptance or reserve the position. <strong>About 5 minutes.</strong></p><div className="bn-grid">{["name|Full name","company|Business / organization","role|Your role","email|Email","phone|Phone","website|Website","linkedin|LinkedIn profile"].map(x=>{const [k,l]=x.split("|");return <label key={k}>{l}<input required={["name","company","email","phone"].includes(k)} value={form[k]} onChange={e=>set(k,e.target.value)}/></label>})}<label>Business category<select required value={form.category} onChange={e=>set("category",e.target.value)}><option value="">Select a category</option>{categories.map(x=><option key={x}>{x}</option>)}<option>Other</option></select></label><label>Years in this field<input value={form.years} onChange={e=>set("years",e.target.value)}/></label><label>Company size<select value={form.companySize} onChange={e=>set("companySize",e.target.value)}><option value="">Select</option><option>Solo</option><option>2–5</option><option>6–20</option><option>21–50</option><option>50+</option></select></label><label>Primary geographic market<input placeholder="e.g. Uxbridge, Durham, York Region" value={form.market} onChange={e=>set("market",e.target.value)}/></label></div></section>}
   {step===2&&<section><p className="bn-kicker">02 — YOUR CONNECTION</p><h1>Tell us where you fit.</h1><label>Are you currently a Mill Run Golf Club member?<select required value={form.millRun} onChange={e=>set("millRun",e.target.value)}><option value="">Select</option><option>Yes</option><option>No</option></select></label><label>How would you describe your connection to the Mill Run community?<textarea value={form.connection} onChange={e=>set("connection",e.target.value)}/></label><label>In a few sentences, what does your business do and who do you primarily serve?<textarea required value={form.business} onChange={e=>set("business",e.target.value)}/></label><label>Why are you interested in joining this group?<textarea required value={form.why} onChange={e=>set("why",e.target.value)}/></label></section>}
   {step===3&&<section><p className="bn-kicker">03 — YOUR VALUE TO THE GROUP</p><h1>Make the room stronger.</h1><p className="bn-lede">Membership is about more than occupying a category. We’re looking for people who make the entire group stronger.</p><label>What can you bring to the group beyond your own products or services?<textarea required value={form.contribution} onChange={e=>set("contribution",e.target.value)}/></label><label>Tell us about a time you helped another business owner or professional when there was no immediate benefit to you.<textarea required value={form.example} onChange={e=>set("example",e.target.value)}/></label><label>What types of people, businesses or opportunities are you particularly well positioned to connect other members with?<textarea required value={form.connections} onChange={e=>set("connections",e.target.value)}/></label><label>What is one area where your experience could genuinely help another member?<textarea value={form.expertise} onChange={e=>set("expertise",e.target.value)}/></label><label>Why should you be selected to represent your business category within the group?<textarea required value={form.whyYou} onChange={e=>set("whyYou",e.target.value)}/></label><label>If you received no direct business from the group for the first six months, what would still make your membership worthwhile?<textarea required value={form.sixMonths} onChange={e=>set("sixMonths",e.target.value)}/></label></section>}
   {step===4&&<section><p className="bn-kicker">04 — COMMITMENT</p><h1>The standard.</h1><label>What would you hope to get from the group personally or professionally?<textarea required value={form.goal} onChange={e=>set("goal",e.target.value)}/></label><label>What other professional categories would be especially valuable to have represented in the group?<textarea value={form.desiredCategories} onChange={e=>set("desiredCategories",e.target.value)}/></label><label>Can you commit to a breakfast meeting approximately twice per month?<select required value={form.commit} onChange={e=>set("commit",e.target.value)}><option value="">Select</option><option>Yes</option><option>No</option></select></label><label>If selected, would you be comfortable with a modest annual membership fee to support the operation and events of the group?<select value={form.feeComfort} onChange={e=>set("feeComfort",e.target.value)}><option value="">Select</option><option>Yes</option><option>No</option><option>Depends on the structure</option></select></label><label>If someone encouraged you to apply, who was it?<input value={form.referrer} onChange={e=>set("referrer",e.target.value)}/></label><label className="bn-check"><input type="checkbox" required checked={form.agree} onChange={e=>set("agree",e.target.checked)}/><span>I understand membership is selective and submitting an application does not guarantee a seat. If accepted, I agree to uphold a standard of professionalism, participation, discretion and genuine contribution.</span></label></section>}
   {step===4&&<details className="bn-review"><summary>Review application before submitting</summary><div><p><b>{form.name||"Your name"}</b> · {form.company||"Business"}</p><p>{form.category||"Category not selected"} · {form.market||"Market not provided"}</p><p><strong>Why join:</strong> {form.why||"—"}</p><p><strong>What you bring:</strong> {form.contribution||"—"}</p><p><strong>Why you:</strong> {form.whyYou||"—"}</p></div></details>}{submitError&&<div className="bn-submiterror" role="alert">{submitError}</div>}<footer className="bn-formnav">{step>1?<button type="button" className="bn-back" onClick={()=>setStep(s=>s-1)}>Back</button>:<span/>}{step<4?<button type="button" className="bn-primary" onClick={next}>Continue <ChevronRight size={17}/></button>:<button className="bn-primary" type="submit" disabled={submitting}>{submitting?"Submitting…":"Submit application"} {!submitting&&<ArrowRight size={17}/>}</button>}</footer>
 </form></main>;
 return <main className="bn"><Helmet><title>{BRAND} | Private Business Networking at Mill Run</title><meta name="description" content="Good business goes both ways. A private business and referral network built around trusted introductions, shared expertise and mutual growth."/><meta property="og:title" content="GOOD GOOD Business Network | Mill Run"/><meta property="og:description" content="Good business goes both ways. A private business and referral network built around trusted introductions, shared expertise and mutual growth."/><meta property="og:image" content="https://northsidegta.ca/Images/good-good-business-network-og.jpg"/><meta property="og:image:width" content="1200"/><meta property="og:image:height" content="630"/><meta property="og:image:alt" content="GOOD GOOD Business Network — Good business goes both ways. Founding chapter at Mill Run."/><meta property="og:type" content="website"/><meta property="og:url" content="https://northsidegta.ca/business-network"/><meta name="twitter:card" content="summary_large_image"/><meta name="twitter:title" content="GOOD GOOD Business Network | Mill Run"/><meta name="twitter:description" content="Good business goes both ways. A private business and referral network built around trusted introductions, shared expertise and mutual growth."/><meta name="twitter:image" content="https://northsidegta.ca/Images/good-good-business-network-og.jpg"/><link rel="canonical" href="https://northsidegta.ca/business-network"/></Helmet>
  <header className="bn-nav"><div className="bn-wordmark"><span className="bn-mark">GG</span><span><b>GOOD GOOD</b><small>BUSINESS NETWORK</small></span></div><nav><a href="#membership">Membership</a><a href="#categories">Categories</a><a href="#standard">The Standard</a></nav><button className="bn-navapply" onClick={()=>setOpen(true)}>Apply for membership</button></header>
  <section className="bn-hero"><div className="bn-hero-inner"><p className="bn-kicker">GOOD BUSINESS GOES BOTH WAYS · MILL RUN</p><h1>The right people.<br/><em>At the same table.</em></h1><p className="bn-hero-copy">A private network of carefully selected business owners and professionals built around trusted introductions, shared expertise and mutual growth.</p><button className="bn-primary" onClick={()=>setOpen(true)}>Apply for membership <ArrowRight size={18}/></button><p className="bn-note">One seat per business category · Mill Run members given preference</p></div><div className="bn-hero-side"><span>01</span><p>Good business<br/>goes both ways.</p></div></section>
  <section className="bn-position"><p className="bn-kicker">NOT ANOTHER NETWORKING GROUP</p><h2>We don’t trade leads.<br/><em>We make introductions.</em></h2><p>A referral should mean something. Every introduction carries a member’s reputation with it. Good Good is built for trusted relationships—not collecting business cards.</p></section><section className="bn-statement" id="standard"><p className="bn-kicker">THE STANDARD</p><h2>What you bring<br/><em>matters.</em></h2><div><p>This isn't a room full of prospects.</p><p>Members are expected to make introductions, share expertise, open doors, offer perspective and actively look for opportunities to help one another.</p><strong>The question isn't only what the group can do for you. It's what you can do for the group.</strong></div></section>
  <section className="bn-process"><p className="bn-kicker">HOW MEMBERSHIP WORKS</p><div>{["Apply","Review","Conversation","Invitation","Seat awarded"].map((x,i)=><span key={x}><b>{String(i+1).padStart(2,"0")}</b>{x}</span>)}</div></section><section className="bn-meetings"><div><p className="bn-kicker">THE MEETINGS</p><h2>Business first.<br/><em>Relationships always.</em></h2></div><div className="bn-meetingfacts"><p><b>Breakfast at Mill Run</b><span>Approximately twice monthly</span></p><p><b>60–75 minutes</b><span>Focused, structured and useful</span></p><p><b>Business-focused</b><span>Introductions, discussion and shared expertise</span></p></div></section><section className="bn-principles" id="membership">{principles.map(({icon:Icon,n,title,text})=><article key={n}><div><Icon size={21}/><span>{n}</span></div><h3>{title}</h3><p>{text}</p></article>)}</section>
  <section className="bn-code"><p className="bn-kicker">THE MEMBER STANDARD</p><div><h3>Show up.</h3><h3>Contribute.</h3><h3>Protect trust.</h3><h3>Create opportunity.</h3></div><p>Category exclusivity is earned through active participation and continued alignment with the standard.</p></section><section className="bn-categories" id="categories"><div><p className="bn-kicker">MEMBERSHIP CATEGORIES</p><h2>One category.<br/>One seat.</h2><p>Open means applications are being considered—not that the first applicant gets the position.</p></div><div className="bn-category-list">{categories.map((x,i)=><div key={x}><span>{String(i+1).padStart(2,"0")}</span><strong>{x}</strong><small>{x==="Real Estate"?"REPRESENTED":"APPLICATIONS OPEN"}</small></div>)}</div></section>
  <section className="bn-founders"><p className="bn-kicker">FOUNDING MEMBERS · MILL RUN · 2026</p><h2>Help set<br/><em>the standard.</em></h2><p>The first members won’t simply join Good Good. They’ll establish what membership means for everyone who follows.</p></section><section className="bn-cta"><p className="bn-kicker">YOUR SEAT AT THE TABLE</p><h2>Think you'd make<br/>the room stronger?</h2><p>We select for reputation, experience, fit and—most importantly—the value you're prepared to bring to other members.</p><button className="bn-light" onClick={()=>setOpen(true)}>Start your application <ArrowRight size={18}/></button></section>
  <footer className="bn-footer"><div className="bn-wordmark"><span className="bn-mark">GG</span><span><b>GOOD GOOD</b><small>BUSINESS NETWORK</small></span></div><p>Good Good Business Network · Founding chapter at Mill Run</p><span>Est. 2026</span></footer>
 </main>
}